### ISSUE TITLE
Problem with update lesson 2

### ISSUE THREAD

**Issue by ELSW56** [fxjollois/cours-sql#7]
Hello @fxjollois 

I've noticed that you've moved former page 2 of lesson 2 (case when) to page 4 of the same lesson.
The trouble is that some exercises of page 3 (dates) need this notion to be known to find a solution (just like the names of the week days).

Regards
@ELSW56

**Comment by fxjollois** [comment]
Hi @ELSW56 

I just see your message. I change the questions in page 3 to avoid this problem.

Thanks for your message
@fxjollois
